services:
  libretranslate:
    container_name: libretranslate
    image: libretranslate/libretranslate:latest
    ports:
      - "4000:4000"
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', './venv/bin/python scripts/healthcheck.py']
      interval: 10s
      timeout: 4s
      retries: 4
      start_period: 5s
    tty: true
    # Add/override args if needed, e.g. --ssl
    # command: --ssl --ga-id MY-GA-ID --req-limit 100 --char-limit 500
    # Enable this block to persist API keys to a volume
     environment:
       - LT_API_KEYS=true
       - LT_API_KEYS_DB_PATH=/app/db/api_keys.db
    environment:
      - LT_UPDATE_MODELS=true
      - LT_LOAD_ONLY=en,fr,ru,fa,ar,es,zh
    volumes:
      - libretranslate_api_keys:/app/db
      # Keep models cached to avoid re-downloading on startup
      - libretranslate_models:/home/libretranslate/.local:rw

volumes:
  libretranslate_api_keys:
  libretranslate_models: